/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import * as nestAccessControl from "nest-access-control";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import * as gqlUserRoles from "../../auth/gqlUserRoles.decorator";
import * as abacUtil from "../../auth/abac.util";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { CreateAllocationArgs } from "./CreateAllocationArgs";
import { UpdateAllocationArgs } from "./UpdateAllocationArgs";
import { DeleteAllocationArgs } from "./DeleteAllocationArgs";
import { AllocationFindManyArgs } from "./AllocationFindManyArgs";
import { AllocationFindUniqueArgs } from "./AllocationFindUniqueArgs";
import { Allocation } from "./Allocation";
import { AllocationService } from "../allocation.service";

@graphql.Resolver(() => Allocation)
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
export class AllocationResolverBase {
  constructor(
    protected readonly service: AllocationService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Allocation",
    action: "read",
    possession: "any",
  })
  async _allocationsMeta(
    @graphql.Args() args: AllocationFindManyArgs
  ): Promise<MetaQueryPayload> {
    const results = await this.service.count({
      ...args,
      skip: undefined,
      take: undefined,
    });
    return {
      count: results,
    };
  }

  @graphql.Query(() => [Allocation])
  @nestAccessControl.UseRoles({
    resource: "Allocation",
    action: "read",
    possession: "any",
  })
  async allocations(
    @graphql.Args() args: AllocationFindManyArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<Allocation[]> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "Allocation",
    });
    const results = await this.service.findMany(args);
    return results.map((result) => permission.filter(result));
  }

  @graphql.Query(() => Allocation, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Allocation",
    action: "read",
    possession: "own",
  })
  async allocation(
    @graphql.Args() args: AllocationFindUniqueArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<Allocation | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "own",
      resource: "Allocation",
    });
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return permission.filter(result);
  }

  @graphql.Mutation(() => Allocation)
  @nestAccessControl.UseRoles({
    resource: "Allocation",
    action: "create",
    possession: "any",
  })
  async createAllocation(
    @graphql.Args() args: CreateAllocationArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<Allocation> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "create",
      possession: "any",
      resource: "Allocation",
    });
    const invalidAttributes = abacUtil.getInvalidAttributes(
      permission,
      args.data
    );
    if (invalidAttributes.length) {
      const properties = invalidAttributes
        .map((attribute: string) => JSON.stringify(attribute))
        .join(", ");
      const roles = userRoles
        .map((role: string) => JSON.stringify(role))
        .join(",");
      throw new apollo.ApolloError(
        `providing the properties: ${properties} on ${"Allocation"} creation is forbidden for roles: ${roles}`
      );
    }
    // @ts-ignore
    return await this.service.create({
      ...args,
      data: args.data,
    });
  }

  @graphql.Mutation(() => Allocation)
  @nestAccessControl.UseRoles({
    resource: "Allocation",
    action: "update",
    possession: "any",
  })
  async updateAllocation(
    @graphql.Args() args: UpdateAllocationArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<Allocation | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "update",
      possession: "any",
      resource: "Allocation",
    });
    const invalidAttributes = abacUtil.getInvalidAttributes(
      permission,
      args.data
    );
    if (invalidAttributes.length) {
      const properties = invalidAttributes
        .map((attribute: string) => JSON.stringify(attribute))
        .join(", ");
      const roles = userRoles
        .map((role: string) => JSON.stringify(role))
        .join(",");
      throw new apollo.ApolloError(
        `providing the properties: ${properties} on ${"Allocation"} update is forbidden for roles: ${roles}`
      );
    }
    try {
      // @ts-ignore
      return await this.service.update({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Allocation)
  @nestAccessControl.UseRoles({
    resource: "Allocation",
    action: "delete",
    possession: "any",
  })
  async deleteAllocation(
    @graphql.Args() args: DeleteAllocationArgs
  ): Promise<Allocation | null> {
    try {
      // @ts-ignore
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
